### ISSUE TITLE
msp430_usb_uart_bridge updates for BeagleConnect LeashPCB rev C

### ISSUE THREAD

**Issue by jadonk** [jadonk/beagleconnect#26]
@FionaYu20180326 , can you ask Baozhu to provide a pull request to https://github.com/statropy/msp430F55xx_usb_uart_bridge with whatever fixes he applied to get it to work on this rev of hardware?

cc @statropy

**Comment by Pillar1989** [comment]
@jadonk  @FionaYu20180326   https://github.com/statropy/msp430F55xx_usb_uart_bridge/pull/8/commits/9c2b5fda9b54ffd6990d389bb0c5cc5a703fa5fa 
I've submitted it here.
