### ISSUE TITLE
HW: Leash PCB rev C: mikrobus connector rotated

### ISSUE THREAD

**Issue by jadonk** [jadonk/beagleconnect#29]
It seems the mikroBUS socket on the side of the board with the buttons is facing the wrong way. The mikroBUS add-on boards should extend *away* from the buttons as not to cover them up. This is wrong for sure.

The mikroBUS socket on the USB/battery side of the board faces away from the USB/battery, which is probably fine. Originally, the thought was to have the top/bottom side connectors facing opposite directions, but this is probably better due to assumptions likely to be made regarding the board orientation. We can discuss.

cc @FionaYu20180326

**Comment by FionaYu20180326** [comment]
Sure. Let's talk about this and modify the PCB placement.

**Comment by jadonk** [comment]
The rev C2 release did not fix this layout issue.

![image](https://user-images.githubusercontent.com/9018/97925205-fb7e6d80-1d2e-11eb-9e5f-aad8dc30076a.png)

**Comment by jadonk** [comment]
Rev C2 placement fix:

![image](https://user-images.githubusercontent.com/9018/99301310-be7ca580-281b-11eb-89c1-db8f99f2a05f.png)

![image](https://user-images.githubusercontent.com/9018/99301321-c3415980-281b-11eb-8f16-bfffbcb9688a.png)
