### ISSUE TITLE
Add MSP430 DFU mode via button press

### ISSUE THREAD

**Issue by statropy** [jadonk/beagleconnect#3]
Pressing the USER1 button during USB insertion should put the MSP430 into USB DFU (firmware update) mode. The PUR pin needs to be pulled up to trigger this mode. See launchpad schematic for BSL button example:

![Screen Shot 2020-07-24 at 1 54 13 PM](https://user-images.githubusercontent.com/919837/88420678-40504b00-cdb5-11ea-884c-5d66f9f2dae9.png)

**Comment by jadonk** [comment]
@ChrisGammell is this change in the rev C schematic? Will you update today or should we ask @FionaYu20180326 at Seeed to fix?

**Comment by statropy** [comment]
Looks complete to me, I think this can be closed

**Comment by ChrisGammell** [comment]
Yes, this was fixed in c925208, it didn't pick up on the issue number (I had tagged #4 and #5 in my commit)
