### ISSUE TITLE
HW: Leash PCB rev C: kicad_pcb file not up to date

### ISSUE THREAD

**Issue by statropy** [jadonk/beagleconnect#31]
The hw/Leash/LeashPCB.kicad_pcb file does not match the Rev C board layout.

Error when opening hw/Leash/LeashPCB.sch
![Screen Shot 2020-10-19 at 10 50 33 AM](https://user-images.githubusercontent.com/919837/96467511-fd0d4900-11f8-11eb-8afa-2168dd368598.png)

**Comment by FionaYu20180326** [comment]
This may because of the different components library. We are trying to fix it, and will update Git once done.

**Comment by statropy** [comment]
More importantly the PCB layout does not match the Rev C board. I really need this to be able to trace through and test hardware. Even if there are errors, please update the kicad_pcb file to the one used to make Rev C

**Comment by FionaYu20180326** [comment]
Updated. In case that there may meet some issues if we cover old version, so I created a new folder. Please check #34
