### ISSUE TITLE
HW: buck-only regulator only operates down to 3.5V

### ISSUE THREAD

**Issue by jadonk** [jadonk/beagleconnect#36]
When using a LiPo battery, the life is severely limited due to the lack of a boost regulator.

**Comment by jadonk** [comment]
See https://github.com/jadonk/beagleconnect/issues/41

**Comment by Ddevendra** [comment]
does this issue still exists, if yes, I believe it could be solved by some of these methods

- changing voltage conversion IC to
	- [LTC3440](https://www.analog.com/en/products/ltc3440.html#product-overview)
	- [TPS61200](https://www.ti.com/product/TPS61200)
_These are some standalone ICs for single cell power management_

- using VLDO voltage regulator (useful only if entire board can operate on complete voltage range 3.3v-3.0v)

- using PowerMUX like [TPS2116](https://www.ti.com/product/TPS2116)

**Comment by jadonk** [comment]
No, we switched to an "ideal diode".
