### ISSUE TITLE
UART Pins for BSL

### ISSUE THREAD

**Issue by statropy** [jadonk/beagleconnect#5]
The CC1352R serial bootloader (BSL) can only use pins DIO12 (CC1352R RX) and DIO13 (CC1352R TX). These pins should be connected to the MSP430 UART pins P4.4 (MSP430 TX) and P4.5 (MSP430 RX).

The CC1352R only has 2 UARTs available, so one must be shared with the external connector and the MSP430. Additionally, so that there is not contention for the UART pins, the MSP430 needs a method of switching the drive of the UART from the external connector to the MSP430 when USB is enumerated. This will prevent a UART connection to a module when connected via USB on that header.

**Comment by statropy** [comment]
DIO12/DIO13 of CC1352R are switched in c925208247cc354a4dd9d04e9ffbb444a79c473b.

**Comment by jadonk** [comment]
> DIO12/DIO13 of CC1352R are switched in [c925208](https://github.com/jadonk/beagleconnect/commit/c925208247cc354a4dd9d04e9ffbb444a79c473b).

Is this comment documentation or a request for correction?

**Comment by statropy** [comment]
This needs to be fixed
