### ISSUE TITLE
MSP430 Spy-Bi-Wire connections

### ISSUE THREAD

**Issue by statropy** [jadonk/beagleconnect#6]
The simplest and default connection for MSP430 program/debug is the Spy-Bi-Wire interface, outlined in https://www.ti.com/lit/ug/slau278af/slau278af.pdf page 23 (screenshot below). The 4 connections needed are

|Signal | MSP430 | Tag Connect |
|---------|-------|-------|
| RST/NMI/SBWTDIO | 48 | 1 |
| TEST/SBWTCK | 47 | 7 |
| GND | | 9 |
| VCC |  | 4 |

The JTAG signals do not need to be connected, but the JTAG signals can still be routed to the connector using DNP 0-Ohm resistors. As long as the default mode is Spy-Bi-Wire.

<img width="734" alt="Screen Shot 2020-07-27 at 11 14 45 AM" src="https://user-images.githubusercontent.com/919837/88559907-6b2be080-cffb-11ea-80d4-796745d3c52d.png">

**Comment by jadonk** [comment]
@ChrisGammell are you making this change today or should we just ask @FionaYu20180326 at Seeed?
